version: '2'

services:
  app:
    container_name: reminder_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: uvicorn api:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./app/:/usr/src/app/

  worker:
    container_name: worker_reminder
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: celery -A reminder worker -l info
    volumes:
      - ./app/:/usr/src/app/

  celery-beat:
    container_name: beat_reminder
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: celery -A reminder beat -l info
    volumes:
      - ./app/:/usr/src/app/

  redis:
    container_name: "redis_reminder"
    image: docker.io/bitnami/redis:6.2
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
    redis_data:
      driver: local